const notes = [
  { id: 0, name: "f", fullName: "f5", ledger: "upper" },
  { id: 1, name: "e", fullName: "e5", ledger: "upper" },
  { id: 2, name: "d", fullName: "d5", ledger: "upper" },
  { id: 3, name: "c", fullName: "c5", ledger: "upper" },
  { id: 4, name: "b", fullName: "b4", ledger: "upper" },
  { id: 5, name: "a", fullName: "a4", ledger: "upper" },
  { id: 6, name: "g", fullName: "g4", ledger: "middle" },
  { id: 7, name: "f", fullName: "f4", ledger: "middle" },
  { id: 8, name: "e", fullName: "e4", ledger: "middle" },
  { id: 9, name: "d", fullName: "d4", ledger: "middle" },
  { id: 10, name: "c", fullName: "c4", ledger: "middle" },
  { id: 11, name: "b", fullName: "b3", ledger: "middle" },
  { id: 12, name: "a", fullName: "a3", ledger: "middle" },
  { id: 13, name: "g", fullName: "g3", ledger: "middle" },
  { id: 14, name: "f", fullName: "f3", ledger: "middle" },
  { id: 15, name: "e", fullName: "e3", ledger: "middle" },
  { id: 16, name: "d", fullName: "d3", ledger: "middle" },
  { id: 17, name: "c", fullName: "c3", ledger: "lower" },
  { id: 18, name: "b", fullName: "b2", ledger: "lower" },
  { id: 19, name: "a", fullName: "a2", ledger: "lower" },
  { id: 20, name: "g", fullName: "g2", ledger: "lower" },
  { id: 21, name: "f", fullName: "f2", ledger: "lower" },
  { id: 22, name: "e", fullName: "e2", ledger: "lower" }
];
